// flow-typed signature: dfed8a7aa932b012fcc416d3957908bb
// flow-typed version: <<STUB>>/bunyan-request_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bunyan-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bunyan-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bunyan-request/example' {
  declare module.exports: any;
}

declare module 'bunyan-request/example/index' {
  declare module.exports: any;
}

declare module 'bunyan-request/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bunyan-request/example.js' {
  declare module.exports: $Exports<'bunyan-request/example'>;
}
declare module 'bunyan-request/example/index.js' {
  declare module.exports: $Exports<'bunyan-request/example/index'>;
}
declare module 'bunyan-request/index' {
  declare module.exports: $Exports<'bunyan-request'>;
}
declare module 'bunyan-request/index.js' {
  declare module.exports: $Exports<'bunyan-request'>;
}
declare module 'bunyan-request/test.js' {
  declare module.exports: $Exports<'bunyan-request/test'>;
}
