// flow-typed signature: ec39536656dc0b91b745dfb42a0fd2f0
// flow-typed version: <<STUB>>/debounce_vhttps://github.com/component/debounce/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'debounce/index' {
  declare module.exports: $Exports<'debounce'>;
}
declare module 'debounce/index.js' {
  declare module.exports: $Exports<'debounce'>;
}
