// flow-typed signature: 2e3d6dfe2a190feed5b1339339dbe68a
// flow-typed version: <<STUB>>/fontfaceobserver_v^2.0.8/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fontfaceobserver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fontfaceobserver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fontfaceobserver/externs' {
  declare module.exports: any;
}

declare module 'fontfaceobserver/fontfaceobserver' {
  declare module.exports: any;
}

declare module 'fontfaceobserver/fontfaceobserver.standalone' {
  declare module.exports: any;
}

declare module 'fontfaceobserver/src/descriptors' {
  declare module.exports: any;
}

declare module 'fontfaceobserver/src/observer' {
  declare module.exports: any;
}

declare module 'fontfaceobserver/src/promise' {
  declare module.exports: any;
}

declare module 'fontfaceobserver/src/ruler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fontfaceobserver/externs.js' {
  declare module.exports: $Exports<'fontfaceobserver/externs'>;
}
declare module 'fontfaceobserver/fontfaceobserver.js' {
  declare module.exports: $Exports<'fontfaceobserver/fontfaceobserver'>;
}
declare module 'fontfaceobserver/fontfaceobserver.standalone.js' {
  declare module.exports: $Exports<'fontfaceobserver/fontfaceobserver.standalone'>;
}
declare module 'fontfaceobserver/src/descriptors.js' {
  declare module.exports: $Exports<'fontfaceobserver/src/descriptors'>;
}
declare module 'fontfaceobserver/src/observer.js' {
  declare module.exports: $Exports<'fontfaceobserver/src/observer'>;
}
declare module 'fontfaceobserver/src/promise.js' {
  declare module.exports: $Exports<'fontfaceobserver/src/promise'>;
}
declare module 'fontfaceobserver/src/ruler.js' {
  declare module.exports: $Exports<'fontfaceobserver/src/ruler'>;
}
