// flow-typed signature: c3df29a4ea2b7412764559653aa60e4b
// flow-typed version: <<STUB>>/lorem-ipsum_v^1.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lorem-ipsum'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lorem-ipsum' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lorem-ipsum/bin/lorem-ipsum.bin' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/lib/clipper' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/lib/dictionary' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/lib/generator' {
  declare module.exports: any;
}

declare module 'lorem-ipsum/test/test-random' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lorem-ipsum/bin/lorem-ipsum.bin.js' {
  declare module.exports: $Exports<'lorem-ipsum/bin/lorem-ipsum.bin'>;
}
declare module 'lorem-ipsum/lib/clipper.js' {
  declare module.exports: $Exports<'lorem-ipsum/lib/clipper'>;
}
declare module 'lorem-ipsum/lib/dictionary.js' {
  declare module.exports: $Exports<'lorem-ipsum/lib/dictionary'>;
}
declare module 'lorem-ipsum/lib/generator.js' {
  declare module.exports: $Exports<'lorem-ipsum/lib/generator'>;
}
declare module 'lorem-ipsum/test/test-random.js' {
  declare module.exports: $Exports<'lorem-ipsum/test/test-random'>;
}
