// flow-typed signature: ef641f8e4c3920ad1b0f771269456d5e
// flow-typed version: <<STUB>>/map-props_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'map-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'map-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'map-props/dist/map-props' {
  declare module.exports: any;
}

declare module 'map-props/dist/map-props.min' {
  declare module.exports: any;
}

declare module 'map-props/dist/react-redux' {
  declare module.exports: any;
}

declare module 'map-props/dist/react-redux.min' {
  declare module.exports: any;
}

declare module 'map-props/dist/redux-form' {
  declare module.exports: any;
}

declare module 'map-props/dist/redux-form.min' {
  declare module.exports: any;
}

declare module 'map-props/lib/index' {
  declare module.exports: any;
}

declare module 'map-props/lib/mapProps' {
  declare module.exports: any;
}

declare module 'map-props/lib/util' {
  declare module.exports: any;
}

declare module 'map-props/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'map-props/dist/map-props.js' {
  declare module.exports: $Exports<'map-props/dist/map-props'>;
}
declare module 'map-props/dist/map-props.min.js' {
  declare module.exports: $Exports<'map-props/dist/map-props.min'>;
}
declare module 'map-props/dist/react-redux.js' {
  declare module.exports: $Exports<'map-props/dist/react-redux'>;
}
declare module 'map-props/dist/react-redux.min.js' {
  declare module.exports: $Exports<'map-props/dist/react-redux.min'>;
}
declare module 'map-props/dist/redux-form.js' {
  declare module.exports: $Exports<'map-props/dist/redux-form'>;
}
declare module 'map-props/dist/redux-form.min.js' {
  declare module.exports: $Exports<'map-props/dist/redux-form.min'>;
}
declare module 'map-props/lib/index.js' {
  declare module.exports: $Exports<'map-props/lib/index'>;
}
declare module 'map-props/lib/mapProps.js' {
  declare module.exports: $Exports<'map-props/lib/mapProps'>;
}
declare module 'map-props/lib/util.js' {
  declare module.exports: $Exports<'map-props/lib/util'>;
}
declare module 'map-props/webpack.config.js' {
  declare module.exports: $Exports<'map-props/webpack.config'>;
}
