// flow-typed signature: 7424b0b80aab737faedfa35ab06b3809
// flow-typed version: <<STUB>>/node-object-hash_v^1.1.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-object-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-object-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-object-hash/objectSorter' {
  declare module.exports: any;
}

declare module 'node-object-hash/v0/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-object-hash/index' {
  declare module.exports: $Exports<'node-object-hash'>;
}
declare module 'node-object-hash/index.js' {
  declare module.exports: $Exports<'node-object-hash'>;
}
declare module 'node-object-hash/objectSorter.js' {
  declare module.exports: $Exports<'node-object-hash/objectSorter'>;
}
declare module 'node-object-hash/v0/index.js' {
  declare module.exports: $Exports<'node-object-hash/v0/index'>;
}
