// flow-typed signature: 18f2d591b46edeec8ceec7f2fa7c6b0c
// flow-typed version: <<STUB>>/normalize.css_v^5.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
