// flow-typed signature: 408658e8fb5168e442c4f30b5c4f3cc5
// flow-typed version: <<STUB>>/postcss-inline-svg_v^2.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-inline-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-inline-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-inline-svg/dist/postcss-inline-svg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-inline-svg/dist/postcss-inline-svg.js' {
  declare module.exports: $Exports<'postcss-inline-svg/dist/postcss-inline-svg'>;
}
