// flow-typed signature: 8fd04e96d56a7f205c9a16381ad25fec
// flow-typed version: <<STUB>>/postcss-assets_v^4.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-assets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-assets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-assets/lib/quote' {
  declare module.exports: any;
}

declare module 'postcss-assets/lib/unescape-css' {
  declare module.exports: any;
}

declare module 'postcss-assets/lib/unquote' {
  declare module.exports: any;
}

declare module 'postcss-assets/test/assets' {
  declare module.exports: any;
}

declare module 'postcss-assets/test/quote' {
  declare module.exports: any;
}

declare module 'postcss-assets/test/unescape-css' {
  declare module.exports: any;
}

declare module 'postcss-assets/test/unquote' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-assets/index' {
  declare module.exports: $Exports<'postcss-assets'>;
}
declare module 'postcss-assets/index.js' {
  declare module.exports: $Exports<'postcss-assets'>;
}
declare module 'postcss-assets/lib/quote.js' {
  declare module.exports: $Exports<'postcss-assets/lib/quote'>;
}
declare module 'postcss-assets/lib/unescape-css.js' {
  declare module.exports: $Exports<'postcss-assets/lib/unescape-css'>;
}
declare module 'postcss-assets/lib/unquote.js' {
  declare module.exports: $Exports<'postcss-assets/lib/unquote'>;
}
declare module 'postcss-assets/test/assets.js' {
  declare module.exports: $Exports<'postcss-assets/test/assets'>;
}
declare module 'postcss-assets/test/quote.js' {
  declare module.exports: $Exports<'postcss-assets/test/quote'>;
}
declare module 'postcss-assets/test/unescape-css.js' {
  declare module.exports: $Exports<'postcss-assets/test/unescape-css'>;
}
declare module 'postcss-assets/test/unquote.js' {
  declare module.exports: $Exports<'postcss-assets/test/unquote'>;
}
