// flow-typed signature: e7f58940967e6c4ad9bf688aa85ca85b
// flow-typed version: <<STUB>>/postcss-browser-reporter_v^0.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-browser-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-browser-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-browser-reporter/index' {
  declare module.exports: $Exports<'postcss-browser-reporter'>;
}
declare module 'postcss-browser-reporter/index.js' {
  declare module.exports: $Exports<'postcss-browser-reporter'>;
}
