// flow-typed signature: 9bfa26ab9daacc2dac1065bfbc22abcb
// flow-typed version: <<STUB>>/postcss-url_v^5.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-url/index' {
  declare module.exports: $Exports<'postcss-url'>;
}
declare module 'postcss-url/index.js' {
  declare module.exports: $Exports<'postcss-url'>;
}
