// flow-typed signature: 7b2cd886208775cb8e8074c9a085a31d
// flow-typed version: <<STUB>>/react-router_vnext/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/matchPath' {
  declare module.exports: any;
}

declare module 'react-router/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router/Prompt' {
  declare module.exports: any;
}

declare module 'react-router/Redirect' {
  declare module.exports: any;
}

declare module 'react-router/Route' {
  declare module.exports: any;
}

declare module 'react-router/Router' {
  declare module.exports: any;
}

declare module 'react-router/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router/Switch' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router' {
  declare module.exports: any;
}

declare module 'react-router/umd/react-router.min' {
  declare module.exports: any;
}

declare module 'react-router/withRouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/index' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/index.js' {
  declare module.exports: $Exports<'react-router'>;
}
declare module 'react-router/matchPath.js' {
  declare module.exports: $Exports<'react-router/matchPath'>;
}
declare module 'react-router/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router/MemoryRouter'>;
}
declare module 'react-router/Prompt.js' {
  declare module.exports: $Exports<'react-router/Prompt'>;
}
declare module 'react-router/Redirect.js' {
  declare module.exports: $Exports<'react-router/Redirect'>;
}
declare module 'react-router/Route.js' {
  declare module.exports: $Exports<'react-router/Route'>;
}
declare module 'react-router/Router.js' {
  declare module.exports: $Exports<'react-router/Router'>;
}
declare module 'react-router/StaticRouter.js' {
  declare module.exports: $Exports<'react-router/StaticRouter'>;
}
declare module 'react-router/Switch.js' {
  declare module.exports: $Exports<'react-router/Switch'>;
}
declare module 'react-router/umd/react-router.js' {
  declare module.exports: $Exports<'react-router/umd/react-router'>;
}
declare module 'react-router/umd/react-router.min.js' {
  declare module.exports: $Exports<'react-router/umd/react-router.min'>;
}
declare module 'react-router/withRouter.js' {
  declare module.exports: $Exports<'react-router/withRouter'>;
}
