// flow-typed signature: 7e480da34a0aafe4832c1cedcab9fa68
// flow-typed version: <<STUB>>/react-router-server_v^2.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-server/build/components/AsyncRenderer' {
  declare module.exports: any;
}

declare module 'react-router-server/build/components/fetchState' {
  declare module.exports: any;
}

declare module 'react-router-server/build/components/Module' {
  declare module.exports: any;
}

declare module 'react-router-server/build/components/ServerStateProvider' {
  declare module.exports: any;
}

declare module 'react-router-server/build/index' {
  declare module.exports: any;
}

declare module 'react-router-server/build/module/cache' {
  declare module.exports: any;
}

declare module 'react-router-server/build/module/info' {
  declare module.exports: any;
}

declare module 'react-router-server/build/module/load' {
  declare module.exports: any;
}

declare module 'react-router-server/build/module/preload' {
  declare module.exports: any;
}

declare module 'react-router-server/build/renderer/renderPass' {
  declare module.exports: any;
}

declare module 'react-router-server/build/renderer/renderToStaticMarkup' {
  declare module.exports: any;
}

declare module 'react-router-server/build/renderer/renderToString' {
  declare module.exports: any;
}

declare module 'react-router-server/build/stats/extractModules' {
  declare module.exports: any;
}

declare module 'react-router-server/build/utils/dirname' {
  declare module.exports: any;
}

declare module 'react-router-server/build/utils/isNode' {
  declare module.exports: any;
}

declare module 'react-router-server/build/utils/join' {
  declare module.exports: any;
}

declare module 'react-router-server/build/utils/removeDuplicateModules' {
  declare module.exports: any;
}

declare module 'react-router-server/build/utils/validateStats' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-server/build/components/AsyncRenderer.js' {
  declare module.exports: $Exports<'react-router-server/build/components/AsyncRenderer'>;
}
declare module 'react-router-server/build/components/fetchState.js' {
  declare module.exports: $Exports<'react-router-server/build/components/fetchState'>;
}
declare module 'react-router-server/build/components/Module.js' {
  declare module.exports: $Exports<'react-router-server/build/components/Module'>;
}
declare module 'react-router-server/build/components/ServerStateProvider.js' {
  declare module.exports: $Exports<'react-router-server/build/components/ServerStateProvider'>;
}
declare module 'react-router-server/build/index.js' {
  declare module.exports: $Exports<'react-router-server/build/index'>;
}
declare module 'react-router-server/build/module/cache.js' {
  declare module.exports: $Exports<'react-router-server/build/module/cache'>;
}
declare module 'react-router-server/build/module/info.js' {
  declare module.exports: $Exports<'react-router-server/build/module/info'>;
}
declare module 'react-router-server/build/module/load.js' {
  declare module.exports: $Exports<'react-router-server/build/module/load'>;
}
declare module 'react-router-server/build/module/preload.js' {
  declare module.exports: $Exports<'react-router-server/build/module/preload'>;
}
declare module 'react-router-server/build/renderer/renderPass.js' {
  declare module.exports: $Exports<'react-router-server/build/renderer/renderPass'>;
}
declare module 'react-router-server/build/renderer/renderToStaticMarkup.js' {
  declare module.exports: $Exports<'react-router-server/build/renderer/renderToStaticMarkup'>;
}
declare module 'react-router-server/build/renderer/renderToString.js' {
  declare module.exports: $Exports<'react-router-server/build/renderer/renderToString'>;
}
declare module 'react-router-server/build/stats/extractModules.js' {
  declare module.exports: $Exports<'react-router-server/build/stats/extractModules'>;
}
declare module 'react-router-server/build/utils/dirname.js' {
  declare module.exports: $Exports<'react-router-server/build/utils/dirname'>;
}
declare module 'react-router-server/build/utils/isNode.js' {
  declare module.exports: $Exports<'react-router-server/build/utils/isNode'>;
}
declare module 'react-router-server/build/utils/join.js' {
  declare module.exports: $Exports<'react-router-server/build/utils/join'>;
}
declare module 'react-router-server/build/utils/removeDuplicateModules.js' {
  declare module.exports: $Exports<'react-router-server/build/utils/removeDuplicateModules'>;
}
declare module 'react-router-server/build/utils/validateStats.js' {
  declare module.exports: $Exports<'react-router-server/build/utils/validateStats'>;
}
