// flow-typed signature: 35566f2a46cb9986bc828909891998d5
// flow-typed version: <<STUB>>/react-router-dom_vnext/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-dom/BrowserRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/HashRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/Link' {
  declare module.exports: any;
}

declare module 'react-router-dom/matchPath' {
  declare module.exports: any;
}

declare module 'react-router-dom/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/NavLink' {
  declare module.exports: any;
}

declare module 'react-router-dom/Prompt' {
  declare module.exports: any;
}

declare module 'react-router-dom/Redirect' {
  declare module.exports: any;
}

declare module 'react-router-dom/Route' {
  declare module.exports: any;
}

declare module 'react-router-dom/Router' {
  declare module.exports: any;
}

declare module 'react-router-dom/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/Switch' {
  declare module.exports: any;
}

declare module 'react-router-dom/umd/react-router-dom' {
  declare module.exports: any;
}

declare module 'react-router-dom/umd/react-router-dom.min' {
  declare module.exports: any;
}

declare module 'react-router-dom/withRouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-dom/BrowserRouter.js' {
  declare module.exports: $Exports<'react-router-dom/BrowserRouter'>;
}
declare module 'react-router-dom/HashRouter.js' {
  declare module.exports: $Exports<'react-router-dom/HashRouter'>;
}
declare module 'react-router-dom/index' {
  declare module.exports: $Exports<'react-router-dom'>;
}
declare module 'react-router-dom/index.js' {
  declare module.exports: $Exports<'react-router-dom'>;
}
declare module 'react-router-dom/Link.js' {
  declare module.exports: $Exports<'react-router-dom/Link'>;
}
declare module 'react-router-dom/matchPath.js' {
  declare module.exports: $Exports<'react-router-dom/matchPath'>;
}
declare module 'react-router-dom/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router-dom/MemoryRouter'>;
}
declare module 'react-router-dom/NavLink.js' {
  declare module.exports: $Exports<'react-router-dom/NavLink'>;
}
declare module 'react-router-dom/Prompt.js' {
  declare module.exports: $Exports<'react-router-dom/Prompt'>;
}
declare module 'react-router-dom/Redirect.js' {
  declare module.exports: $Exports<'react-router-dom/Redirect'>;
}
declare module 'react-router-dom/Route.js' {
  declare module.exports: $Exports<'react-router-dom/Route'>;
}
declare module 'react-router-dom/Router.js' {
  declare module.exports: $Exports<'react-router-dom/Router'>;
}
declare module 'react-router-dom/StaticRouter.js' {
  declare module.exports: $Exports<'react-router-dom/StaticRouter'>;
}
declare module 'react-router-dom/Switch.js' {
  declare module.exports: $Exports<'react-router-dom/Switch'>;
}
declare module 'react-router-dom/umd/react-router-dom.js' {
  declare module.exports: $Exports<'react-router-dom/umd/react-router-dom'>;
}
declare module 'react-router-dom/umd/react-router-dom.min.js' {
  declare module.exports: $Exports<'react-router-dom/umd/react-router-dom.min'>;
}
declare module 'react-router-dom/withRouter.js' {
  declare module.exports: $Exports<'react-router-dom/withRouter'>;
}
