// flow-typed signature: 7091531388b3cb7ad43dad25807eebee
// flow-typed version: <<STUB>>/react-waypoint_v^5.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-waypoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-waypoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-waypoint/build/waypoint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-waypoint/build/waypoint.js' {
  declare module.exports: $Exports<'react-waypoint/build/waypoint'>;
}
