// flow-typed signature: 9ab89223a394fee84421aba732ae7506
// flow-typed version: <<STUB>>/reactotron-react-js_v^1.6.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactotron-react-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactotron-react-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactotron-react-js/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactotron-react-js/dist/index.js' {
  declare module.exports: $Exports<'reactotron-react-js/dist/index'>;
}
