// flow-typed signature: ba7d405e89bbb414ba1b39040286f92d
// flow-typed version: <<STUB>>/timekeeper_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timekeeper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'timekeeper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'timekeeper/lib/timekeeper' {
  declare module.exports: any;
}

declare module 'timekeeper/test/node.support' {
  declare module.exports: any;
}

declare module 'timekeeper/test/timekeeper.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'timekeeper/lib/timekeeper.js' {
  declare module.exports: $Exports<'timekeeper/lib/timekeeper'>;
}
declare module 'timekeeper/test/node.support.js' {
  declare module.exports: $Exports<'timekeeper/test/node.support'>;
}
declare module 'timekeeper/test/timekeeper.test.js' {
  declare module.exports: $Exports<'timekeeper/test/timekeeper.test'>;
}
